MOD_EJECUCION=ConClientela
Ruta=/fichtemcomp/ei/descargas/kytl/
File=/fichtemcomp/ei/descargas/kytl/ConClientela/ConClientela_processed.csv
Servicio=ConClientela
SuccessAction=LEAVE
Delta=No
Preprocesado=Si
Accion=VariablesGlobales
NomScript=Delta
ArgScri1=No
Accion=Script
NomScript=QuitarNulos
PreArgScri1=$FILES
ArgScri1=ConClientela/ConClientela.csv
Accion=Script
JDKV=17
NomPaquete1=ControlCargaDatos.jar
NomPaquete2=javacsv.jar
NomClaseJava=controlcargadatos.ControlCase
ServicioJava=PreprocessedClientela
PreArgJava1=$FILES
ArgJava1=ConClientela/ConClientela.csv
PreArgJava2=$LOG
ArgJava2=ConClientela_preprocess_summary.log
PreArgJava3=/ei/kytl/online/multipais/multicanal/dat/properties
ArgJava3=fillingRules_ConClientela.csv
Libreria1=ojdbc8.jar
Libreria2=common-lang3.jar
Libreria3=log4j.jar
Accion=Java
JDKV=17
NomPaquete1=RDR_PLSQL.jar
NomClaseJava=rdr_plsql.ConClientela
ServicioJava=ConClientela
PreArgJava1=$FILES
ArgJava1=ConClientela/ConClientela_processed.csv
Libreria1=ojdbc8.jar
Libreria2=common-lang3.jar
Libreria3=log4j.jar
Accion=Java
JDKV=17
NomPaquete1=RDR_Report.jar
NomClaseJava=rdr_report.CreateReport
ServicioJava=ReportClientela
PreArgJava1=/ei/kytl/online/multipais/multicanal/dat/properties
ArgJava1=select.properties
ArgJava2=ConClientela
Libreria1=ojdbc8.jar
Libreria2=common-lang3.jar
Libreria3=log4j.jar
Accion=Java
NomScript=Unix2Dos
PreArgScri1=$FILES
ArgScri1=ConClientela/Reporte_ConClientela.csv
Accion=Script

