MOD_EJECUCION=LEI
Servicio=LEI
Ruta=/fichtemcomp/ei/descargas/kytl/
File=/fichtemcomp/ei/descargas/kytl/LEI/LEI.csv
BusinessFeed=CargaLEI
SuccessAction=LEAVE
MessageType=CargaLEI
Delta=Si
Stop=Ok
Accion=VariablesGlobales
NomScript=LanzaScriptBash
ArgScri1=gleif.sh
Accion=Script
NomScript=LanzaScriptBash
ArgScri1=LEI.sh
Accion=Script
NomScript=Delta
ArgScri1=Si
Accion=Script
NomEvento=MDX
Accion=Evento
JDKV=17
NomPaquete1=RDR_Report.jar
NomClaseJava=rdr_report.CreateReport
ServicioJava=ReporteCargaLEI
PreArgJava1=/ei/kytl/online/multipais/multicanal/dat/properties
ArgJava1=select.properties
ArgJava2=LEI
Libreria1=ojdbc8.jar
Libreria2=common-lang3.jar
Libreria3=log4j.jar
Accion=Java
NomScript=LanzaScriptBash
ArgScri1=Comprobar_fichero_LEI.sh
Accion=Script
NomEvento=Errores
Accion=Evento

