MOD_EJECUCION=ExtraccionGenericaCONT
Servicio=ExtraccionGenericaCONT
Accion=VariablesGlobales
JDKV=17
NomPaquete1=ExtraccionGenericaOtherEntities.jar
NomClaseJava=extracciongenericaotherentities.Ppal
ServicioJava=ExtraccionGenericaCONT_log
ArgJava1=2
PreArgJava2=/ei/kytl/online/multipais/multicanal/dat/properties
ArgJava2=log4jExtraccionGenericaCON.properties
ArgJava3=20
ArgJava4=/fichtemcomp/ei/descargas/kytl/extracciongenerica
PreArgJava5=/fichtemcomp/ei/descargas/kytl/extracciongenerica
ArgJava5=ExtraccionContingenciaCONT.xml.tmp
ArgJava6=CONT
ArgJava7=/ei/kytl/online/multipais/multicanal/cfg/entorno
Libreria1=ojdbc8.jar
Libreria2=commons-io-2.5.jar
Libreria3=log4j.jar
Libreria4=xdb.jar
Libreria5=xmlparserv2-11.1.1.2.0-patched.jar
Libreria6=commons-dbcp-1.4.jar
Libreria7=commons-pool-1.5.4.jar
Accion=Java
NomScript=XSLT_TO_XML
PreArgScri1=/fichtemcomp/ei/descargas/kytl/extracciongenerica/CONT/
ArgScri1=ExtraccionContingenciaCONT.xml
PreArgScri2=/ei/kytl/online/multipais/multicanal/dat/properties/
ArgScri2=sait.xsl
PreArgScri3=/fichtemcomp/ei/descargas/kytl/extracciongenerica/CONT/SAIT
ArgScri3=RDR_contactosSAIT.xml
Accion=Script

