MOD_EJECUCION=GestionAlertas
Ruta=/fichtemcomp/ei/descargas/kytl/GestionAlertas
File=
Servicio=GestionAlertas
Accion=VariablesGlobales
NomPaquete1=ConexionBD.jar
NomPaquete2=RDR_AlertasBarrido.jar
NomClaseJava=main.Ppal
ServicioJava=GestionAlertas_BarridoAlertas
ArgJava1=2
PreArgJava2=/ei/kytl/online/multipais/multicanal/dat/properties
ArgJava2=log4jAlertasBarrido.properties
ArgJava3=PROCESOS
Libreria1=ojdbc8.jar
Libreria2=common-lang3.jar
Libreria3=log4j.jar
Accion=Java
NomPaquete1=ConexionBD.jar
NomPaquete2=RDR_AlertasCocinado.jar
NomClaseJava=main.Ppal
ServicioJava=GestionAlertas_cocinado
ArgJava1=2
PreArgJava2=/ei/kytl/online/multipais/multicanal/dat/properties
ArgJava2=log4jAlertasCocinado.properties
ArgJava3=PROCESOS
Libreria1=ojdbc8.jar
Libreria2=common-lang3.jar
Libreria3=log4j.jar
Libreria4=apache-commons-lang.jar
Libreria5=commons-collections4-4.1.jar
Libreria6=poi-ooxml-schemas-3.17.jar
Libreria7=poi-3.17.jar
Libreria8=poi-ooxml-3.17.jar
Libreria9=poi-scratchpad-3.17.jar
Libreria10=xmlbeans-2.3.0.jar
Accion=Java
NomEvento=Workflow
NomWorkflow=RDR_AlertasEnvio
Accion=Evento

