MOD_EJECUCION=RDR_Refinitiv_REQ_RES
id=MULTI
idType=ORG_ID
requestType=ratingsRequest
vreqOid=BATCH_RATINGS
Accion=VariablesGlobales
NomEvento=Workflow
NomWorkflow=Refinitiv_Request_Response
Accion=Evento
