MOD_EJECUCION=Refinitiv_Request_Response
id=MULTI
idType=MULTI
requestType=issueRequest
vreqOid=MULTI_ISSUE
Accion=VariablesGlobales
NomEvento=Workflow
NomWorkflow=Refinitiv_Request_Response
Accion=Evento

