MOD_EJECUCION=CargaSectorizacionT2
Servicio=CargaSectorizacionT2
Accion=VariablesGlobales
NomPaquete1=ConexionBD.jar
NomPaquete2=RDR_SectorizacionEmisores.jar
NomClaseJava=main.java.sectorizacionemisores.T2_Sect_Bloom_Refinit_POST
ServicioJava=T2_Sect_Bloom_Refinit_POST
ArgJava1=2
PreArgJava2=/ei/kytl/online/multipais/multicanal/dat/properties
ArgJava2=log4jCargaSectorizacion.properties
PreArgJava3=/fichtemcomp/ei/descargas/kytl/T1_CatalogValuesTaxonomy
ArgJava3=T1_CatalogValuesTaxonomy.csv
PreArgJava4=/fichtemcomp/ei/descargas/kytl/T2_RelValuesTaxonomy
ArgJava4=T2_RelValuesTaxonomy.csv
ArgJava5=T2
Libreria1=log4j.jar
Libreria2=ojdbc8.jar
Accion=Java
