MOD_EJECUCION=CargaSectorizacionT3
Servicio=CargaSectorizacionT3
Accion=VariablesGlobales
JDKV=17
NomPaquete1=ConexionBD.jar
NomPaquete2=RDR_SectorizacionEmisores.jar
NomClaseJava=main.java.sectorizacionemisores.T3_SectorizacionADA
ServicioJava=T3_SectorizacionADA
ArgJava1=2
PreArgJava2=/ei/kytl/online/multipais/multicanal/dat/properties
ArgJava2=log4jCargaSectorizacion.properties
ArgJava3=---
PreArgJava4=/fichtemcomp/ei/descargas/kytl/T3_IssuersIssuesCustomer
ArgJava4=T3_IssuersIssuesCustomer.csv
ArgJava5=T3
Libreria1=log4j.jar
Libreria2=ojdbc8.jar
Accion=Java

