MOD_EJECUCION=oficinas
Ruta=/fichtemcomp/@@ENV@@/descargas/kytl/
File=/fichtemcomp/@@ENV@@/descargas/kytl/oficinas/oficinas_processed.csv
Servicio=oficinas
BusinessFeed=Oficina
SuccessAction=LEAVE
MessageType=OFC
Delta=Si
Preprocesado=Si
MDX=Si
Errores=No
Reporte=Si
Accion=VariablesGlobales
NomScript=LimpiarOficinas
PreArgScri1=$FILES
ArgScri1=oficinas
Accion=Script
NomScript=Delta
ArgScri1=Si
Accion=Script
NomPaquete1=ControlCargaDatos.jar
NomPaquete2=javacsv.jar
NomClaseJava=ControlCase
ServicioJava=PreprocessedOficinas
PreArgJava1=$FILES
ArgJava1=oficinas/oficinas.csv
PreArgJava2=$LOG
ArgJava2=oficinas_preprocess_summary.log
PreArgJava3=$CONF
ArgJava3=fillingRules_oficinas.csv
Libreria1=ojdbc8.jar
Libreria2=common-lang3.jar
Libreria3=log4j.jar
Accion=Java
NomEvento=MDX
Accion=Evento
NomEvento=Errores
Accion=Evento
NomPaquete1=RDR_Report.jar
NomClaseJava=CreateReport
ServicioJava=ReportOficinas
PreArgJava1=$CONF
ArgJava1=select.properties
ArgJava2=oficinas
Libreria1=ojdbc8.jar
Libreria2=common-lang3.jar
Libreria3=log4j.jar
Accion=Java
NomScript=Unix2Dos
PreArgScri1=$FILES
ArgScri1=oficinas/Reporte_oficinas.csv
Accion=Script


