MOD_EJECUCION=Reubicacion
Ruta=/fichtemcomp/@@ENV@@/descargas/kytl/
File=/fichtemcomp/@@ENV@@/descargas/kytl/Reubicacion/Reubicacion_processed.csv
Servicio=Reubicacion
BusinessFeed=Reubicacion
SuccessAction=LEAVE
MessageType=Reubicacion
Accion=VariablesGlobales
NomScript=LimpiarReubicacion
PreArgScri1=$FILES
ArgScri1=Reubicacion
Accion=Script
NomPaquete1=ControlCargaDatos.jar
NomPaquete2=javacsv.jar
NomClaseJava=ControlCase
ServicioJava=Reubicacion
PreArgJava1=$FILES
ArgJava1=Reubicacion/Reubicacion.tmp
PreArgJava2=$LOG
ArgJava2=Reubicacion_preprocess_summary.log
PreArgJava3=$CONF
ArgJava3=fillingRules_Reubicacion.csv
Libreria1=ojdbc8.jar
Libreria2=common-lang3.jar
Libreria3=log4j.jar
Accion=Java
NomEvento=Workflow
NomWorkflow=RDR_Reubicacion
Accion=Evento
NomPaquete1=RDR_Report.jar
NomClaseJava=CreateReport
ServicioJava=ReportReubicacion
PreArgJava1=$CONF
ArgJava1=select.properties
ArgJava2=Reubicacion
Libreria1=ojdbc8.jar
Libreria2=common-lang3.jar
Libreria3=log4j.jar
Accion=Java
NomScript=Unix2Dos
PreArgScri1=$FILES
ArgScri1=Reubicacion/Reporte_Reubicacion.csv
Accion=Script

