MOD_EJECUCION=TradPlazas
Ruta=/fichtemcomp/@@ENV@@/descargas/kytl/
File=/fichtemcomp/@@ENV@@/descargas/kytl/TradPlazas/TradPlazas_processed.csv
Servicio=TradPlazas
BusinessFeed=Plaza
SuccessAction=LEAVE
MessageType=PLZTRAD
Delta=No
Preprocesado=Si
MDX=Si
Errores=No
Reporte=No
Accion=VariablesGlobales 
NomScript=Delta
ArgScri1=No
Accion=Script
NomPaquete1=ControlCargaDatos.jar
NomPaquete2=javacsv.jar
NomClaseJava=ControlCase
ServicioJava=PreprocessedTradPlazas
PreArgJava1=$FILES
ArgJava1=TradPlazas/TradPlazas.csv
PreArgJava2=$LOG
ArgJava2=TradPlazas_preprocess_summary.log
PreArgJava3=$CONF
ArgJava3=fillingRules_TradPlazas.csv
Libreria1=ojdbc8.jar
Libreria2=common-lang3.jar
Libreria3=log4j.jar
Accion=Java
NomEvento=MDX
Accion=Evento

