MOD_EJECUCION=AltamiraMexicoSend
Servicio=AltamiraMexicoSend
Accion=VariablesGlobales
JDKV=17
NomPaquete1=ConexionBD.jar
NomPaquete2=AltamiraMexicoConciliacion.jar
NomClaseJava=altamiramexicoconciliacion.MexicoEnvio
ServicioJava=AltamiraMexicoSend_log
ArgJava1=2
PreArgJava2=/ei/kytl/online/multipais/multicanal/dat/properties
ArgJava2=log4jAltamiraMexicoConciliacion.properties
ArgJava3=20
PreArgJava4=/fichtemcomp/ei/descargas/kytl/AltamiraMexico/send/
ArgJava4=RDR_clientesYYYYMMDD.csv
Libreria1=ojdbc8.jar
Libreria2=commons-lang3.jar
Libreria3=log4j.jar
Accion=Java
