#datos de configuracion del sh
#rutas
# antes_JAVA64_=/usr/local/@@ENV@@/jdk1.7.0_75/bin
JAVA64=/usr/local/@@ENV@@/jdk1.8.0_152/bin
LIB_PATH=/@@ENV@@/kytl/online/multipais/multicanal/lib
PATH_PROPERTIES=/@@ENV@@/kytl/online/multipais/multicanal/dat/properties
DIR_JAR=/@@ENV@@/kytl/online/multipais/multicanal/jar
PATH_SCRT=/@@ENV@@/kytl/online/multipais/multicanal/scrt
#archivos
JAR_FILE=anna_download.jar
NAME_LOG4J_PROPERTIES=log4j-anna-download.properties
CREDENTIALS_FILE=/@@ENV@@/kytl/online/multipais/multicanal/cfg/entorno/credentials.xml
CREDENTIALS_FILE_SUB=/@@ENV@@/kytl/online/multipais/multicanal/cfg/entorno/
#datos anna
anna.path.download=kytl/file-download/totv
#pathAnnaPR=kytl\/file-download\/totv\/ 
#pathAnnaEP=kytl\/file-download\/totv-v2\/
anna.prefix=OC-OP-OM-FF
#directorios de salida
anna.downloads=/fichtemcomp/@@ENV@@/descargas/kytl/issues/Anna/downloads/
anna.records=/fichtemcomp/@@ENV@@/descargas/kytl/issues/Anna/records/
anna.output=/fichtemcomp/@@ENV@@/descargas/kytl/issues/Anna/output/
anna.path.log=/fichtemcomp/@@ENV@@/descargas/kytl/issues/Anna/logs/
anna.nombre.log=anna_download_log.log
#Token

anna.rutaTokenA=$SHIVA
anna.rutaTokenB=https://de.xmas.cibgateway.igrupobbva
shivaPP=https:\/\/pp.xmas.cibgateway.igrupobbva
shivaPR=https:\/\/pr.xmas.cibgateway.igrupobbva
shivaEP=https:\/\/ei.xmas.cibgateway.igrupobbva
#ficheros de salida
FILEOUT=MDX-ANNA
FILEOUTSUB=SUB-MDX-ANNA
