MOD_EJECUCION=Refundicion
Ruta=/fichtemcomp/ei/descargas/kytl/
File=/fichtemcomp/ei/descargas/kytl/Refundicion/Refundicion_processed.csv
Servicio=Refundicion
BusinessFeed=Refundicion
SuccessAction=LEAVE
MessageType=Refundicion
Delta=Si
Tipologia=TOTAL
Accion=VariablesGlobales
NomScript=Delta
ArgScri1=Si
Accion=Script
NomScript=LimpiarRefundicion
PreArgScri1=$FILES
ArgScri1=Refundicion
Accion=Script
JDKV=17
NomPaquete1=ControlCargaDatos.jar
NomPaquete2=javacsv.jar
NomClaseJava=controlcargadatos.ControlCase
ServicioJava=Refundicion
PreArgJava1=$FILES
ArgJava1=Refundicion/Refundicion.tmp
PreArgJava2=$LOG
ArgJava2=Refundicion_preprocess_summary.log
PreArgJava3=$CONF
ArgJava3=fillingRules_Refundicion.csv
Libreria1=ojdbc8.jar
Libreria2=common-lang3.jar
Libreria3=log4j.jar
Accion=Java
NomEvento=Workflow
NomWorkflow=RDR_Refundicion
Accion=Evento
NomEvento=Workflow
NomWorkflow=RDR_Clientela460
Accion=Evento
NomEvento=Errores
Accion=Evento
JDKV=17
NomPaquete1=RDR_Report.jar
NomClaseJava=rdr_report.CreateReport
ServicioJava=ReportRefundicion
PreArgJava1=$CONF
ArgJava1=select.properties
ArgJava2=Refundicion
Libreria1=ojdbc8.jar
Libreria2=common-lang3.jar
Libreria3=log4j.jar
Accion=Java
NomScript=Unix2Dos
PreArgScri1=$FILES
ArgScri1=Refundicion/Reporte_Refundicion.csv
Accion=Script

