MOD_EJECUCION=AlertasDerivadosRefinitiv
Ruta=/fichtemcomp/ei/descargas/kytl/
Servicio=AlertasDerivadosRefinitiv
Accion=VariablesGlobales
NomProperty=GestionAlertas
ArgProp1=GestionAlertas_DERIVADOS_REFINITIV
ArgProp2=PROCESOS-DERIVADOS_REFINITIV
Accion=Property
