MOD_EJECUCION=Refinitiv_Request_Response
id=MULTI
idType=UNDLY
requestType=issueRequest
vreqOid=UNDLY_ISSUES_ENRICHMENT
Accion=VariablesGlobales
NomEvento=Workflow
NomWorkflow=Refinitiv_Request_Response
Accion=Evento

