MOD_EJECUCION=AgreementsBBVA
Servicio=AgreementsBBVA
Accion=VariablesGlobales
NomScript=XSLT_TO_XML
PreArgScri1=/fichtemcomp/ei/descargas/kytl/LAGR
ArgScri1=BBVAContracts.xml
PreArgScri2=/ei/kytl/online/multipais/multicanal/dat/properties
ArgScri2=Agreements_To_Mentor.xsl
PreArgScri3=/fichtemcomp/ei/descargas/kytl/LAGR/MENTOR
ArgScri3=BBVAContracts_mentor.xml
Accion=Script
NomScript=XSLT_TO_XML
PreArgScri1=/fichtemcomp/ei/descargas/kytl/LAGR/MENTOR
ArgScri1=BBVAContracts_mentor.xml
PreArgScri2=/ei/kytl/online/multipais/multicanal/dat/properties
ArgScri2=Agreements_To_Mentor_Productos.xsl
PreArgScri3=/fichtemcomp/ei/descargas/kytl/LAGR/MENTOR
ArgScri3=BBVAContracts_mentor_prods.xml
Accion=Script
NomScript=Borrar
PreArgScri1=/fichtemcomp/ei/descargas/kytl/LAGR/MENTOR
ArgScri1=BBVAContracts_mentor.xml
Accion=Script
NomScript=XSLT_TO_XML
PreArgScri1=/fichtemcomp/ei/descargas/kytl/LAGR/MENTOR
ArgScri1=BBVAContracts_mentor_prods.xml
PreArgScri2=/ei/kytl/online/multipais/multicanal/dat/properties
ArgScri2=Agreements_Normalize.xsl
PreArgScri3=/fichtemcomp/ei/descargas/kytl/LAGR/MENTOR
ArgScri3=BBVAContracts_mentor1.xml
Accion=Script
NomScript=Borrar
PreArgScri1=/fichtemcomp/ei/descargas/kytl/LAGR/MENTOR
ArgScri1=BBVAContracts_mentor_prods.xml
Accion=Script
NomScript=XSLT_TO_XML
PreArgScri1=/fichtemcomp/ei/descargas/kytl/LAGR/MENTOR
ArgScri1=BBVAContracts_mentor1.xml
PreArgScri2=/ei/kytl/online/multipais/multicanal/dat/properties
ArgScri2=Agreements_Nodes.xsl
PreArgScri3=/fichtemcomp/ei/descargas/kytl/LAGR/MENTOR
ArgScri3=BBVAContracts_mentor2.xml
Accion=Script
NomScript=Borrar
PreArgScri1=/fichtemcomp/ei/descargas/kytl/LAGR/MENTOR
ArgScri1=BBVAContracts_mentor1.xml
Accion=Script
NomScript=MoverFichero
PreArgScri1=/fichtemcomp/ei/descargas/kytl/LAGR/MENTOR
ArgScri1=BBVAContracts_mentor2.xml
PreArgScri2=/fichtemcomp/ei/descargas/kytl/LAGR/MENTOR
ArgScri2=BBVAContracts_mentor.xml
Accion=Script
NomScript=XSLT_TO_XML
PreArgScri1=/fichtemcomp/ei/descargas/kytl/LAGR
ArgScri1=BBVAContracts.xml
PreArgScri2=/ei/kytl/online/multipais/multicanal/dat/properties
ArgScri2=Agreements_Nodes.xsl
PreArgScri3=/fichtemcomp/ei/descargas/kytl/LAGR
ArgScri3=BBVAContracts_temp.xml
Accion=Script
NomScript=Borrar
PreArgScri1=/fichtemcomp/ei/descargas/kytl/LAGR
ArgScri1=BBVAContracts.xml
Accion=Script
NomScript=MoverFichero
PreArgScri1=/fichtemcomp/ei/descargas/kytl/LAGR
ArgScri1=BBVAContracts_temp.xml
PreArgScri2=/fichtemcomp/ei/descargas/kytl/LAGR
ArgScri2=BBVAContracts.xml
Accion=Script
NomScript=XSLT_TO_XML
PreArgScri1=/fichtemcomp/ei/descargas/kytl/LAGR
ArgScri1=BBVAContracts.xml
PreArgScri2=/ei/kytl/online/multipais/multicanal/dat/properties
ArgScri2=BBVA_Contrats_CSV.xsl
PreArgScri3=/fichtemcomp/ei/descargas/kytl/LAGR
ArgScri3=BBVAContracts.csv
Accion=Script
