MOD_EJECUCION=GestionAlertas
Ruta=/fichtemcomp/ei/descargas/kytl/
Servicio=SSIsAlertFxOnline
Accion=VariablesGlobales
NomEvento=Workflow
NomWorkflow=RDR_SSIS_Fx_Alert_Online
Accion=Evento
NomProperty=GestionAlertas
ArgProp1=GestionAlertas_ALERT_IP_SSI
ArgProp2=PROCESOS-ALERT_IP_SSI
Accion=Property
