TIMEWAIT=5
BusinessFeed=Load_BBG_Ratings
MessageBulkSize=100
MessageType=Load_BBG_Ratings
ParallelFileLoadSub=Parallel File Load Sub
SuccessAction=LEAVE
contact_ANS=errores-funcionalestecnicos.group@bbva.com
contact_USER=errores-funcionalestecnicos.group@bbva.com

